name: 'action-file.io'
description: 'Upload to `file.io`'
author: 'heowc'
inputs:
  position:
    description: 'Base location for finding file'
    required: false
    default: '.'
  file_basename:
    description: 'File name to be created'
    required: false
    default: 'file'
  file_path:
    description: 'Path of the file(s) to upload'
    required: true
  expires:
    description: 'How long files are not deleted. (See https://www.file.io/)'
    required: false
outputs:
  response:
    description: 'Response for curl'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.position }}
    - ${{ inputs.file_basename }}
    - ${{ inputs.file_path }}
    - ${{ inputs.expires }}
branding:
  icon: 'shopping-bag'
  color: 'blue'

